IIC2143 - Ingeniería de Software/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  # Administrador
  get 'admin', to: 'admin#index'

  scope '/admin' do
    get 'usuarios', to: 'perfil#index', as: 'admin_usuarios'
    get 'locales', to: 'admin#ver_locales', as: 'admin_locales'
    delete 'locales/:local_id', to: 'admin#eliminar_local', as: 'admin_delete_local'
    get 'aceptar_locales', to: 'admin#aceptar_locales', as: 'admin_aceptar_locales'
    patch 'aceptar_locales/:local_id', to: 'admin#aceptar_local', as: 'admin_aceptar_local'
    resources :comunas, controller: 'communes'
    resources :gustos, controller: 'interests'
    resources :comentarios, controller: 'comments', only: %i[index destroy]
  end

  # Locales, Menus y Comentarios
  resources :locales, controller: 'locals', as: 'local' do
    resources :menus, only: %i[new create edit update destroy]
    resources :comentarios, controller: 'comments', only: %i[new create destroy]
    resources :valoraciones, controller: 'valuations', only: %i[edit update destroy]
  end
  # Perfil
  # Create
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations' }

  # Ver menus
  get 'locales/:local_id/edit/menus', to: 'menus#show', as: :local_menues

  # Imagenes del local
  get 'locales/:local_id/edit/imagenes', to: 'locals#images', as: :local_images
  patch 'locales/:local_id/edit/imagenes', to: 'locals#update_images', as: :local_add_images
  delete 'locales/:local_id/edit/imagenes/:image_id', to: 'locals#delete_images',
                                                      as: :local_delete_images

  # Ver comentarios
  get 'perfil/:user_id/comentarios', to: 'comments#show', as: :perfil_comentarios
  # Ver valoraciones pendientes
  get 'perfil/:user_id/valoraciones', to: 'perfil#valuations', as: :perfil_valuations

  # Read perfil
  get 'perfil/:user_id', to: 'perfil#show', as: :perfil

  # Update perfil
  get 'perfil/:id/edit', to: 'perfil#edit', as: :perfil_edit
  patch 'perfil/:id', to: 'perfil#update'
  put 'perfil/:id', to: 'perfil#update'

  # Update interes
  patch 'perfil_interest/:id', to: 'perfil#update_interest', as: :perfil_edit_interest
  get 'perfil/:id/:idinterest', to: 'perfil#delete_interest', as: :perfil_delete_interest

  # Update Profile Avatar
  patch 'perfil_avatar/:user_id', to: 'perfil#update_avatar', as: :perfil_update_avatar
  delete 'perfil_avatar/:user_id', to: 'perfil#delete_avatar', as: :perfil_delete_avatar

  # Delete perfil
  delete 'perfil/:id', to: 'perfil#destroy'

  # Match
  # Mostrar perfiles
  get 'match/:id', to: 'matches#index', as: :match
  # Mostrar informacion de los matches del usuario
  get 'match/:id/info', to: 'matches#show', as: :match_info

  # Create match
  get 'match/:id/:idsolicitado', to: 'matches#new', as: :match_new
  # Aceptar/Rechazar match_request
  patch 'perfil/:id/:id_matchrequest', to: 'matches#accept_match', as: :perfil_accept_match

  # CITAS
  # Proponer Cita
  get 'appointment/:id', to: 'appointment#new', as: :new_appointment

  # Crear Cita
  post 'appointment/:id', to: 'appointment#create', as: :create_appointment

  # Aceptar Cita
  put 'perfil/:id/:appointment_id', to: 'appointment#accept', as: :accept_appointment
end

IIC2143 - Ingeniería de Software/app/models/local.rb
class Local < ApplicationRecord
  validates :nombre, :descripcion, presence: true

  has_many_attached :images

  def carousel_photo(input)
    if images[input].variable?
      images[input].variant(resize: '800x480!').processed
    else
      images[input]
    end
  rescue StandardError
    'https://bulma.io/images/placeholders/800x480.png'
  end

  belongs_to :user
  belongs_to :commune
  has_many :menus, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :valuations, dependent: :destroy
end

IIC2143 - Ingeniería de Software/app/controllers/locals_controller.rb
class LocalsController < ApplicationController
  def new
    unless user_signed_in?
      redirect_to local_index_path, notice: 'Debes tener una cuenta para crear un local.'
    else
      if Local.find_by('user_id = ?', current_user.id)
        redirect_to local_index_path, notice: 'Tu cuenta ya tiene un local asociado.'
      else
        @local = Local.new
      end
    end
  end

  def create
    local_params = params.require(:local).permit(:nombre, :descripcion, :commune_id, :telefono, :direccion)
    local_params[:user_id] = current_user.id

    local_direccion = local_params[:direccion]

    require 'opencage/geocoder'
    geocoder = OpenCage::Geocoder.new(api_key: '60c54918b16a4e338ecb409cc525b948')
    results = geocoder.geocode(local_direccion)

    if results.first
      @coordenadas = results.first.coordinates
      local_params[:lat] = @coordenadas[0]
      local_params[:long] = @coordenadas[1]
      @local = Local.new(local_params)
      if @local.save
        redirect_to local_index_path, notice: 'Se ha enviado el formulario del local al administrador. Debes esperar que él acepte el local' 
      else
        redirect_to local_index_path, notice: 'Ha ocurrido un error al crear el local' 
      end
    else 
      redirect_to new_local_path, notice: 'La dirección ingresada no se ha podido encontrar. Se recomienda utilizar direcciones existentes en Google Maps'
    end
  end

  def show
    @local = Local.find(params[:id])
    @cantidad_valoraciones = @local.valuations.where("realizada = true").count
    @promedio = @local.valuations.where("realizada = true").average(:puntuacion)

    unless @promedio
      @promedio = "(El local aún no tiene puntuaciones)"
    else
      @promedio = @promedio.round(1)
      @promedio = " #{@promedio} / 5"
    end


    unless @local.aceptado
      redirect_to local_index_path, notice: 'Este local aún no ha sido aceptado'
    else 
      @menus = @local.menus
      @comentarios = @local.comments
      @images = @local.images
      @empty_images = @images.count == 0
      @one_image = @images.count == 1
    end
  end

  def index
    if params[:valoracion]
      if params[:valoracion] != 'Todas'
        max = params[:valoracion][-1]
        min = params[:valoracion][0]
        @locales = []
        if params[:commune_id] != 'Todas'
          all_locals = Local.where("commune_id = ?", params[:commune_id])
        else
          all_locals = Local.all
        end
        all_locals.each do |local|
          @promedio = local.valuations.where("realizada = true").average(:puntuacion)
          if @promedio 
            @promedio = @promedio.round(1)
            if @promedio >= min.to_i and @promedio <= max.to_i
              @locales = @locales.append(local)
            end
          end
        end
      elsif params[:commune_id] != 'Todas'
        @locales = Local.where("commune_id = ?", params[:commune_id])
      else
        @locales = Local.where("aceptado = true")
      end

    elsif params[:search]
      if params[:search] == ""
        @locales = Local.where("aceptado = true")
      else
        @locales = Local.where("nombre ILIKE ?", "%" + params[:search] + "%")
      end

    else
      @locales = Local.where("aceptado = true")
    end
    @locales = @locales.paginate(page: params[:page], per_page: 6)
  end

  def edit
    @local = Local.find(params[:id])
    @menus = @local.menus
    unless user_signed_in? and current_user.id == Local.find(params[:id]).user_id
      redirect_to local_path(@local.id), notice: 'No puedes acceder a esta página'
    else
      unless @local.aceptado
        redirect_to local_index_path, notice: 'No puedes editar tu local si no ha sido aceptado'
      else
        render
      end
    end
  end

  def images
    @local = Local.find(params[:local_id])
    unless user_signed_in? and current_user.id == @local.user_id
        redirect_to local_path(@local.id), notice: 'No puedes acceder a esta página'
    else
      unless @local.aceptado
          redirect_to local_index_path, notice: "No puedes editar tu local si no ha sido aceptado"
      else
        render
      end
    end
  end

  def update_images
    local_params = params.require(:local).permit(images: [])
    n_imagenes_nuevas = local_params[:images].count
    @local = Local.find(params[:local_id])
    if n_imagenes_nuevas > 5
      redirect_to local_images_path(@local.id), notice: "Solo puedes subir un máximo de 5 imágenes"
      return
    end
    
    n_imagenes = @local.images.count
    if n_imagenes + n_imagenes_nuevas > 5
      redirect_to local_images_path(@local.id), notice: "Tu local ya tiene #{n_imagenes} imágenes, solo puedes cargar #{5-n_imagenes_nuevas} imágenes nuevas"
      return
    end

    @local.images.attach(local_params[:images])
    if @local.images.attached?
      redirect_to local_images_path(@local.id), notice: "Las imágenes han sido agregadas con éxito"
    else
      redirect_to local_images_path(@local.id), notice: "Ha ocurrido un error al agregar las imágenes"
    end
  end

  def delete_images
    @image = ActiveStorage::Blob.find_signed(params[:image_id])
    @image.attachments.first.purge
    @local = Local.find(params[:local_id])
    redirect_to local_images_path(@local.id), notice: "La imagen ha sido eliminada con éxito"
  end

  def update
    local_params = params.require(:local).permit(:descripcion, :telefono)
    @local = Local.find(params[:id])

    if @local.update(local_params)
      redirect_to local_path(@local.id), notice: 'Local editado con éxito'
    else
      redirect_to local_path(@local.id), notice: 'Ocurrió un error al editar el local'
    end
  end

  def destroy
    @local = Local.find(params[:id])
    @local.destroy
    redirect_to local_index_path, notice: 'Local eliminado con éxito'
  end
end

IIC2143 - Ingeniería de Software/app/helpers/locals_helper.rb
module LocalsHelper
end

IIC2143 - Ingeniería de Software/app/views/locals/edit.html.erb
<section class="hero is-danger">
  <div class="hero-body">
    <div class="container">
      <h1 class="title has-text-centered"> Editar el local <%= @local.nombre%> </h1>
      <h2 class="subtitle has-text-centered">En esta sección puedes editar los datos descriptivos de tu local</h2>
      <div class="buttons is-centered">
        <%= link_to 'Volver', local_path(@local.id), class: "button is-link is-rounded"%>
      </div>
    </div>
  </div>
</section>

<div class="tabs is-centered">
  <ul>
    <li class="is-active"><a href="<%= edit_local_path(@local.id) %>">Datos</a></li>
    <li><%= link_to 'Menus', local_menues_path(@local.id) %></li>
    <li><%= link_to 'Imágenes', local_images_path(@local.id) %></li>
  </ul>
</div>

<div class="columns">
  <div class="column is-4"></div>
  <div class="column is-4">
    <div class="box">
      <%= form_with(model: @local, url: local_path(@local.id), method: :patch) do |form| %>
        <div class='field'>
          <%= form.label :descripcion%>
          <%= form.text_area :descripcion, class: "textarea"%>
        </div>
        <div class='field'>
          <%= form.label :telefono%>
          <%= form.text_field :telefono, autofocus: true, autocomplete: "telefono", placeholder: "Telefono", class: "input"%>
        </div>
        <div class='actions'>
          <%= form.submit "Guardar cambios", class: "button is-primary"%>
          <%= link_to "Eliminar local", local_path(@local.id), method: :delete, class: "button is-danger",
          data: {confirm: "¿Estás seguro? \n Esta acción no es reversible"} %>
        </div>
      <%end%>
    </div>
  </div>

  <div class="column is-4"></div>
</div>

IIC2143 - Ingeniería de Software/app/views/locals/images.html.erb
<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>

<section class="hero is-danger">
  <div class="hero-body">
    <div class="container">
      <h1 class="title has-text-centered"> Editar el local <%= @local.nombre%> </h1>
      <h2 class="subtitle has-text-centered"> En esta sección puedes subir hasta cinco imágenes que serán mostradas en la página principal de tu local</h2>
      <div class="buttons is-centered">
        <%= link_to 'Volver', local_path(@local.id), class: "button is-link is-rounded"%>
      </div>
    </div>
  </div>
</section>

<div class="tabs is-centered">
  <ul>
    <li><%= link_to "Datos", edit_local_path(@local.id)%></li>
    <li><%= link_to 'Menus', local_menues_path(@local.id) %></li>
    <li class="is-active"><%= link_to 'Imágenes', local_images_path(@local.id) %></li>
  </ul>
</div>



<div class="columns">
  <div class="column is-2"></div>
  <div class="column is-8">
    <% (0...@local.images.count).each do |image_index| %>
      <div class="box">
        <center>
          <% imagen = @local.images[image_index]%>
          <%= image_tag(@local.carousel_photo(image_index)) %>
        </center>
        <br>
        <center>
          <%= link_to "Eliminar imagen", local_delete_images_path(@local.id, imagen.signed_id), 
          class: "button is-danger", method: :delete, data: {confirm: "¿Estás seguro?" }%>
        </center>
      </div>
    <% end %>
    <div class="box">
      <h1 class="title has-text-centered"> Cargar imágenes </h1>
      <%= form_with(model: @local, url: local_add_images_path(@local.id), method: :patch) do |form| %>
        <div class="file is-centered">
          <label class="file-label">
            <%= form.file_field :images, multiple: true, accept: 'image/jpeg', class: "file-input"%>
            <span class="file-cta">
              <span class="file-icon">
                <i class="fas fa-upload"></i>
              </span>
              <span class="file-label">
                Elige una o varias imágenes...
              </span>
            </span>
          </label>
        </div>
        <br>
        <center>
          <div class="button is-primary">
            <%= form.submit "Guardar Imagenes", class: "button is-primary"%>
          </div>
        </center>
      <% end %>
    </div>
  </div>
  <div class="column is-2"></div>
</div>

IIC2143 - Ingeniería de Software/app/views/locals/new.html.erb
<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>

<section class="hero is-danger">
    <div class="hero-body">
        <div class="container">
            <h1 class="title has-text-centered"> Registrar un nuevo local</h1>
            <h2 class="subtitle has-text-centered"> El formulario será enviado a un administrador, quien puede o no aceptar la solicitud</h2>
            <div class="buttons is-centered">
                <%= link_to "Volver", perfil_path(current_user.id), class: "button is-link is-rounded"%>
            </div>
        </div>
    </div>
</section>

<section class="section">
    <div class="columns">
        <div class="column"></div>
        <div class="column is-4">
            <div class="box">
                <%= form_with(model: @local, url: local_index_path, method: :post) do |form| %>
                    <div class='field'>
                        <span class="icon is-small is-left">
                            <i class="fas fa-address-card"></i>
                        </span>
                        Nombre:
                        <%= form.text_field :nombre, placeholder: "Nombre", class: "input"%>
                    </div>
                    <div class='field'>
                        <span class="icon is-small is-left">
                            <i class="fas fa-mobile-alt"></i>
                        </span>
                        Telefono:
                        <%= form.text_field :telefono, placeholder: "Telefono", class: "input"%>
                    </div>
                    <div class='field'>
                        <span class="icon is-small is-left">
                            <i class="fas fa-map-marker-alt"></i>
                        </span>
                        Direccion (se recomienda exactitud):
                        <%= form.text_field :direccion, placeholder: "Ej: Nueva Pte. 1213, Osorno, Los Lagos", class: "input"%>
                    </div>
                    <div class='field'>
                        <span class="icon is-small is-left">
                            <i class="fas fa-home"></i>
                        </span>
                        Comuna:
                        <div class="select is-fullwidth">
                            <%= form.select(:commune_id, Commune.all.collect {|c| [c.nombre, c.id]}) %>
                        </div>
                    </div>
                    <div class='field'>
                        <span class="icon is-small is-left">
                            <i class="fas fa-question"></i>
                        </span>
                        Descripción:
                        <%= form.text_area :descripcion, placeholder: "Descripción", class: "textarea"%> 
                    </div>
                    <p></p>
                    <div class='actions'>
                        <%= form.submit "Enviar", class: "button is-primary"%>
                    </div>
                <%end%>
            </div>
        </div>
        <div class="column"></div>
    </div>
</section>

IIC2143 - Ingeniería de Software/app/views/locals/show.html.erb
<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

<script>

  var marker;

  function initMap() {
    var myLatLng = {lat: <%=@local.lat%>, lng: <%=@local.long%>};

    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 17,
      center: myLatLng
    });

    var contentString =
    '<h1><b><%=@local.nombre%></b></h1>'+
    '<p><b>Direccion:</b> <%=@local.direccion%></p>'+
    '<p><b>Telefono:</b> <%=@local.telefono%></p>'+
    '<p><b>Descripcion:</b> <%=@local.descripcion%></p>';

    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });  

    marker = new google.maps.Marker({
      position: myLatLng,
      map: map,
      draggable: true,
      animation: google.maps.Animation.DROP,
      title: '<%=@local.nombre%>'
    });
    marker.addListener('click', function(){
      infowindow.open(map, marker);
    });

    marker.addListener('mouseover', toggleBounce);
  }

  function toggleBounce() {
    if (marker.getAnimation() !== null) {
      marker.setAnimation(null);
    } else {
      marker.setAnimation(google.maps.Animation.BOUNCE);
    }
  }
</script>
<script async defer
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBsShmfQR57ZbpPbdBYV0yUiG9NfaAE1q8&callback=initMap">
</script>

<section>
  <div class="hero is-danger">
    <div class="hero-body">
      <h1 class="title has-text-centered"> <%= @local.nombre %></h1>
      <h2 class="subtitle has-text-centered"> <%= @local.descripcion %></h2>
      <h2 class="subtitle has-text-centered"> Comuna: <%= @local.commune.nombre %></h2>
      <h2 class="subtitle has-text-centered"> Teléfono: <%= @local.telefono %></h2>
      <h3 class="subtitle has-text-centered"> Puntuación: <%= @promedio %>
        <%if @cantidad_valoraciones == 1 %>
          de <%= @cantidad_valoraciones %> valoracion
        <%elsif @cantidad_valoraciones != 0%>
          de <%= @cantidad_valoraciones %> valoraciones
        <% end %></p></h3>
      <div class="buttons is-centered">
        <%= link_to 'Volver', local_index_path, class: "button is-link is-rounded"%>
        <% if user_signed_in? and current_user.id == @local.user_id%>
          <%= link_to 'Editar', edit_local_path(@local.id), class: "button is-primary is-rounded"%>
        <% end%>
      </div>
    </div>
    <br>
  </div>
</section>

<section class="section">
  <div class="columns">
  <div class="column is-6">
    <div id="myCarousel" class="carousel slide" data-ride="carousel" style="margin:18px;">
      <% if @empty_images%>
        <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        </ol>

        <div class="carousel-inner">
          <div class="item active">
            <figure class="image is-5by3">
              <img src="https://bulma.io/images/placeholders/800x480.png">
            </figure>
          </div>
        </div>
      <% else %>
        <ol class="carousel-indicators">
          <li data-taget="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <% (1...@images.count).each do |i|%>
            <li data-target="#carouselExampleIndicators" data-slide-to=<%= "#{i}" %>></li>
          <% end %>
        </ol>
        
        <div class="carousel-inner">
          <div class="item active">
            <figure class="image is-5by3">
              <%= image_tag(@local.carousel_photo(0)) %>
            </figure>
          </div>
          <% unless @one_image %>
            <% (1...@images.count).each do |index_image|%>
              <div class="item">
                <figure class="image is-5by3">
                  <%= image_tag(@local.carousel_photo(index_image)) %>
                </figure>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>

      <!-- Left and right controls -->
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
  <div class="column"></div>
      <div id="map" style="width:45%;display:block;margin:30px;"></div>
  </div>

<div class="columns">
  <div class="column"></div>
  <div class="column is-two-thirds">
    <div class="box">
    <h1 class="title has-text-centered"> Menus ofrecidos </h1>
      <div class="media-content">
        <div class="content">
          <table class="table">
            <thead>
              <tr>
                <th>Menú</th>
                <th>Descripción</th>
                <th>Precio</th>
              </tr>
            </thead> 
            <tbody>
              <% @menus.each do |menu| %>
                <tr>
                  <td><%= menu.nombre %></td>
                  <td><%= menu.descripcion%></td>
                  <td>$<%= menu.precio%></td>
                </tr>
              <% end %>
            </tbody> 
          </table> 

        </div>
      </div>
    </div>
  </div>
  <div class="column"></div>
</div>
</section>

<div class="notification is-fluid is-danger">
  <h1 class="title has-text-centered"> Comentarios </h1>
  <div class="buttons is-centered">
    <% if user_signed_in? and current_user.id != @local.user_id %>
      <%=link_to "Nuevo Comentario", new_local_comentario_path(@local.id), class: "button is-primary is-rounded"%>
    <% end %>
  </div>
</div>
<div class="columns">
  <div class="column"></div>
  <div class="column is-two-thirds">
    <% @comentarios.each do |comentario|%>
    <div class="box">
      <article class="media">
        <div class="media-left">
          <figure class="image is-128x128">
            <% unless comentario.user.avatar.attached? %>
              <img src="https://bulma.io/images/placeholders/128x128.png" alt="Imagen de perfil" class="is-rounded">
            <% else %>
              <%= image_tag comentario.user.comment_avatar, class: "is-rounded" %>
            <% end %>
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <strong><%= comentario.user.nombre %></strong> 
              <small><i><%= comentario.created_at.strftime("%d-%m-%Y")%></i> a las <i><%= comentario.created_at.strftime("%H:%M")%></i></small>
              <br>
              <%= comentario.contenido %>
            </p>
          </div>
          <div class="buttons">
          <% if user_signed_in? and current_user.id == comentario.user_id%>
            <%= link_to 'Eliminar Comentario', local_comentario_path(@local.id, comentario.id), method: :delete, class: "button is-danger"%>
          <% end %>
          </div>
        </div>
      </article>
    </div>
    <% end %>
  </div>
  <div class="column"></div>
</div>
</section>