IIC2143 - Ingeniería de Software/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  # Administrador
  get 'admin', to: 'admin#index'

  scope '/admin' do
    get 'usuarios', to: 'perfil#index', as: 'admin_usuarios'
    get 'locales', to: 'admin#ver_locales', as: 'admin_locales'
    delete 'locales/:local_id', to: 'admin#eliminar_local', as: 'admin_delete_local'
    get 'aceptar_locales', to: 'admin#aceptar_locales', as: 'admin_aceptar_locales'
    patch 'aceptar_locales/:local_id', to: 'admin#aceptar_local', as: 'admin_aceptar_local'
    resources :comunas, controller: 'communes'
    resources :gustos, controller: 'interests'
    resources :comentarios, controller: 'comments', only: %i[index destroy]
  end

  # Locales, Menus y Comentarios
  resources :locales, controller: 'locals', as: 'local' do
    resources :menus, only: %i[new create edit update destroy]
    resources :comentarios, controller: 'comments', only: %i[new create destroy]
    resources :valoraciones, controller: 'valuations', only: %i[edit update destroy]
  end
  # Perfil
  # Create
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations' }

  # Ver menus
  get 'locales/:local_id/edit/menus', to: 'menus#show', as: :local_menues

  # Imagenes del local
  get 'locales/:local_id/edit/imagenes', to: 'locals#images', as: :local_images
  patch 'locales/:local_id/edit/imagenes', to: 'locals#update_images', as: :local_add_images
  delete 'locales/:local_id/edit/imagenes/:image_id', to: 'locals#delete_images',
                                                      as: :local_delete_images

  # Ver comentarios
  get 'perfil/:user_id/comentarios', to: 'comments#show', as: :perfil_comentarios
  # Ver valoraciones pendientes
  get 'perfil/:user_id/valoraciones', to: 'perfil#valuations', as: :perfil_valuations

  # Read perfil
  get 'perfil/:user_id', to: 'perfil#show', as: :perfil

  # Update perfil
  get 'perfil/:id/edit', to: 'perfil#edit', as: :perfil_edit
  patch 'perfil/:id', to: 'perfil#update'
  put 'perfil/:id', to: 'perfil#update'

  # Update interes
  patch 'perfil_interest/:id', to: 'perfil#update_interest', as: :perfil_edit_interest
  get 'perfil/:id/:idinterest', to: 'perfil#delete_interest', as: :perfil_delete_interest

  # Update Profile Avatar
  patch 'perfil_avatar/:user_id', to: 'perfil#update_avatar', as: :perfil_update_avatar
  delete 'perfil_avatar/:user_id', to: 'perfil#delete_avatar', as: :perfil_delete_avatar

  # Delete perfil
  delete 'perfil/:id', to: 'perfil#destroy'

  # Match
  # Mostrar perfiles
  get 'match/:id', to: 'matches#index', as: :match
  # Mostrar informacion de los matches del usuario
  get 'match/:id/info', to: 'matches#show', as: :match_info

  # Create match
  get 'match/:id/:idsolicitado', to: 'matches#new', as: :match_new
  # Aceptar/Rechazar match_request
  patch 'perfil/:id/:id_matchrequest', to: 'matches#accept_match', as: :perfil_accept_match

  # CITAS
  # Proponer Cita
  get 'appointment/:id', to: 'appointment#new', as: :new_appointment

  # Crear Cita
  post 'appointment/:id', to: 'appointment#create', as: :create_appointment

  # Aceptar Cita
  put 'perfil/:id/:appointment_id', to: 'appointment#accept', as: :accept_appointment
end

IIC2143 - Ingeniería de Software/app/models/menu.rb
class Menu < ApplicationRecord
  validates :nombre, :descripcion, :precio, presence: true
  belongs_to :local
end

IIC2143 - Ingeniería de Software/app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def new
    unless user_signed_in? and current_user.id == Local.find(params[:local_id]).user_id
      redirect_to local_index_path, notice: 'No puedes acceder a esta página'
    else
      @menu = Menu.new
      @local = Local.find(params[:local_id])
    end
  end

  def create
    menu_params = params.require(:menu).permit(:nombre, :descripcion, :precio)
    @local_id = params[:local_id]
    menu_params[:local_id] = @local_id
    @menu = Menu.new(menu_params)
    
    if @menu.save
      redirect_to edit_local_path(@local_id), notice: 'El menú ha sido agregado con éxito'

    else
      redirect_to edit_local_path(@local_id), notice: 'Ocurrió un error al agregar un menú'
    end
  end

  def edit
    unless user_signed_in? and current_user.id == Local.find(params[:local_id]).user_id
      redirect_to local_index_path, notice: 'No puedes acceder a esta página'
    else
      @menu = Menu.find(params[:id])
      @local_id = params[:local_id]
    end
  end

  def update
    @menu = Menu.find(params[:id])
    @local_id = params[:local_id]
    menu_params = params.require(:menu).permit(:nombre, :descripcion, :precio)
    if @menu.update(menu_params)
      redirect_to edit_local_path(@local_id), notice: 'El menú ha sido editado con éxito'
    else
      redirect_to edit_local_path(@local_id), notice: 'Ocurrió un error al editar el menú'
    end
  end

  def show
    @local = Local.find(params[:local_id])
    unless user_signed_in? and current_user.id == @local.user_id
      redirect_to local_path(@local.id), notice: 'No puedes acceder a esta página'
    else
      unless @local.aceptado
        redirect_to local_index_path, notice: 'No puedes editar tu local si no ha sido aceptado'
      else
        @menus = @local.menus
        render
      end
    end
  end

  def destroy
    @menu = Menu.find(params[:id])
    @local_id = params[:local_id]
    @menu.destroy
    redirect_to edit_local_path(@local_id), notice: 'El menú ha sido eliminado con éxito'
  end
end

IIC2143 - Ingeniería de Software/app/helpers/menus_helper.rb
module MenusHelper
end

IIC2143 - Ingeniería de Software/app/views/menus/edit.html.erb
<section class="section">
  <div class="columns">
    <div class="column"></div>
    <div class="column is-5">
      <div class="box">
        <h1 class="title has-text-centered"> Editar Menú</h1>
        <%= form_with(model: @menu, url: local_menu_path(@local_id, @menu.id), method: :patch) do |form| %>
          <div class="field">
            Plato:
            <%= form.text_field :nombre, class: "input"%>
          </div>

          <div class="field">
            Descripción:
            <%= form.text_area :descripcion, class: "textarea"%>
         </div>

          <div class="field">
            Precio:
            <%= form.number_field :precio, class: "input"%>
           </div>

          <div class="actions">
            <%= form.submit "Guardar Cambios", class: "button is-primary"%>
            <%= link_to "Volver", local_menues_path(@local_id), class: "button is-link"%>
          </div>
        <% end %>
      </div>
    </div>
    <div class="column"></div>
  </div>
</section>

IIC2143 - Ingeniería de Software/app/views/menus/new.html.erb
<section class="section">
<div class="columns">
  <div class="column"></div>
  <div class="column is-5">
    <div class="box">
      <h1 class="title has-text-centered"> Nuevo menú para <%= @local.nombre %></h1>
      <%= form_with(model: @menu, url: local_menus_path(@local.id), method: :post) do |form| %>

      <div class='field'>
        Nombre:
        <%= form.text_field :nombre, placeholder: "Nombre del menú", class: "input"%>
      </div>

      <div class='field'>
        Descripción:
        <%= form.text_area :descripcion, placeholder: "Ingrese aquí la descripción del menú", class: "textarea"%>
      </div>

      <div class='field'>
        Precio:
        <%= form.number_field :precio, class: "input"%>
      </div>

      <div class="actions">
        <%= form.submit "Crear menú", class: "button is-primary"%>
        <%= link_to "Volver", local_menues_path(@local.id), class: "button is-link"%>
      </div>
    <% end %>
    </div>
  </div>
  <div class="column"></div>
</div>
</section>

IIC2143 - Ingeniería de Software/app/views/menus/show.html.erb
<section class="hero is-danger">
  <div class="hero-body">
    <div class="container">
      <h1 class="title has-text-centered"> Editar el local <%= @local.nombre%> </h1>
      <h2 class="subtitle has-text-centered"> En esta sección puedes editar y agregar los exquisitos menús que ofrece tu local </h2>
      <div class="buttons is-centered">
        <%= link_to 'Volver', local_path(@local.id), class: "button is-link is-rounded"%>
      </div>
    </div>
  </div>
</section>

<div class="tabs is-centered">
  <ul>
    <li><%= link_to "Datos", edit_local_path(@local.id)%></li>
    <li class="is-active"><%= link_to 'Menus', local_menues_path(@local.id) %></li>
    <li><%= link_to 'Imágenes', local_images_path(@local.id) %></li>
  </ul>
</div>

<div class="columns">
  <div class="column is-3"></div>
  <div class="column is-6">
    <div class="box">
      <table class="table">
        <thead>
          <tr>
            <th>Menu</th>
            <th>Descripción</th>
            <th>Precio</th>
            <th>Acciones</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @menus.each do |menu| %>
            <tr>
              <td><%= menu.nombre %></td>
              <td><%= menu.descripcion%></td>
              <td><%= menu.precio %></td>
              <td><%= link_to 'Editar', edit_local_menu_path(@local.id, menu.id), class: "button is-primary"%></td>
              <td><%= link_to 'Eliminar', local_menu_path(@local.id, menu.id), method: :delete, class: "button is-danger",
                      data: { confirm: "¿Estás seguro?"} %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="actions">
        <%= link_to "Agregar menú", new_local_menu_path(@local.id), class: "button is-primary"%>
      </div>
    </div>
  </div>

  <div class="column is-3"></div>
</div>