IIC2143 - Ingeniería de Software/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  # Administrador
  get 'admin', to: 'admin#index'

  scope '/admin' do
    get 'usuarios', to: 'perfil#index', as: 'admin_usuarios'
    get 'locales', to: 'admin#ver_locales', as: 'admin_locales'
    delete 'locales/:local_id', to: 'admin#eliminar_local', as: 'admin_delete_local'
    get 'aceptar_locales', to: 'admin#aceptar_locales', as: 'admin_aceptar_locales'
    patch 'aceptar_locales/:local_id', to: 'admin#aceptar_local', as: 'admin_aceptar_local'
    resources :comunas, controller: 'communes'
    resources :gustos, controller: 'interests'
    resources :comentarios, controller: 'comments', only: %i[index destroy]
  end

  # Locales, Menus y Comentarios
  resources :locales, controller: 'locals', as: 'local' do
    resources :menus, only: %i[new create edit update destroy]
    resources :comentarios, controller: 'comments', only: %i[new create destroy]
    resources :valoraciones, controller: 'valuations', only: %i[edit update destroy]
  end
  # Perfil
  # Create
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations' }

  # Ver menus
  get 'locales/:local_id/edit/menus', to: 'menus#show', as: :local_menues

  # Imagenes del local
  get 'locales/:local_id/edit/imagenes', to: 'locals#images', as: :local_images
  patch 'locales/:local_id/edit/imagenes', to: 'locals#update_images', as: :local_add_images
  delete 'locales/:local_id/edit/imagenes/:image_id', to: 'locals#delete_images',
                                                      as: :local_delete_images

  # Ver comentarios
  get 'perfil/:user_id/comentarios', to: 'comments#show', as: :perfil_comentarios
  # Ver valoraciones pendientes
  get 'perfil/:user_id/valoraciones', to: 'perfil#valuations', as: :perfil_valuations

  # Read perfil
  get 'perfil/:user_id', to: 'perfil#show', as: :perfil

  # Update perfil
  get 'perfil/:id/edit', to: 'perfil#edit', as: :perfil_edit
  patch 'perfil/:id', to: 'perfil#update'
  put 'perfil/:id', to: 'perfil#update'

  # Update interes
  patch 'perfil_interest/:id', to: 'perfil#update_interest', as: :perfil_edit_interest
  get 'perfil/:id/:idinterest', to: 'perfil#delete_interest', as: :perfil_delete_interest

  # Update Profile Avatar
  patch 'perfil_avatar/:user_id', to: 'perfil#update_avatar', as: :perfil_update_avatar
  delete 'perfil_avatar/:user_id', to: 'perfil#delete_avatar', as: :perfil_delete_avatar

  # Delete perfil
  delete 'perfil/:id', to: 'perfil#destroy'

  # Match
  # Mostrar perfiles
  get 'match/:id', to: 'matches#index', as: :match
  # Mostrar informacion de los matches del usuario
  get 'match/:id/info', to: 'matches#show', as: :match_info

  # Create match
  get 'match/:id/:idsolicitado', to: 'matches#new', as: :match_new
  # Aceptar/Rechazar match_request
  patch 'perfil/:id/:id_matchrequest', to: 'matches#accept_match', as: :perfil_accept_match

  # CITAS
  # Proponer Cita
  get 'appointment/:id', to: 'appointment#new', as: :new_appointment

  # Crear Cita
  post 'appointment/:id', to: 'appointment#create', as: :create_appointment

  # Aceptar Cita
  put 'perfil/:id/:appointment_id', to: 'appointment#accept', as: :accept_appointment
end

IIC2143 - Ingeniería de Software/app/controllers/perfil_controller.rb
require 'date'

class PerfilController < ApplicationController

  # Read
  def index
    @users = User.where("admin = false")
    render :layout => 'admin'
  end

  #Show
  def show
    if user_signed_in? and current_user.id == params[:user_id].to_i
      @user = User.find(params[:user_id])
      @local = @user.local
      @commune = @user.commune
      @interests_user = @user.interests
      @interests_all = Interest.all
      @interests_not_user = []

      @interests_all.each do |interest|
        repetido = false
        @interests_user.each do |interest_user|
          if interest_user.nombre == interest.nombre
            repetido = true
            break
          end
        end

        if not repetido
          @interests_not_user << interest
        end
      end

      #Cada vez que entra a su perfil busca posibles match que se hayan hecho mutuamente por casualidad
      @match_nuevos = MatchRequest.where('solicitado_id = ?', @user.id)
      @match_nuevos.each do |m|
        @match_coincidentes = MatchRequest.where('solicitado_id = ? and solicitante_id = ?', m.solicitante_id, @user.id)
        if @match_coincidentes
          @match_coincidentes.each do |m2|
            match = Match.new(user1_id: m2.solicitante_id,
              user2_id: m2.solicitado_id,
              cita_realizada: false)
            match.save!
            m2.destroy
            m.destroy
          end
        end
      end
      @match_nuevos = MatchRequest.where('solicitado_id = ?', @user.id)
      @match_todos = Match.where('user1_id = ? or user2_id = ?', @user.id, @user.id)
    elsif user_signed_in?
      @user = User.find(params[:user_id])
      @interests_user = @user.interests
      @commune = @user.commune
      render "show_incomplete"
    else
      redirect_to root_path, notice: 'No puedes acceder a esta página'
    end
  end

  def valuations
    if user_signed_in? and current_user.id == params[:user_id].to_i
      @pending_valuations = current_user.valuations.where("realizada = false").sort_by(&:fecha)
      @current_date = DateTime.now.to_date
    else
      redirect_to root_path, notice: "No puedes acceder a esta página"
    end
  end

  #Update
  def edit
    unless user_signed_in?
      redirect_to root_path, notice: 'Usted debe ingresar sesión para poder ver el perfil de otro usuario'
    else
      @user = User.find(params[:id])
    end
  end

  def update
    user_params = params.require(:user).permit(:nombre, :email, :descripcion, :edad, :telefono, :commune_id, :genero)

    @user = User.find(params[:id])

    unless user_params[:nombre].empty?
      if @user.update(user_params)
        redirect_to perfil_path(@user.id), notice: 'Datos de usuario actualizados con éxito'

      else
        redirect_to perfil_path(@user.id), notice: 'Ocurrio un error al actualizar los datos'
      end
    else
      redirect_to perfil_path(@user.id), notice: 'Tu nombre no puede ser vacío'
    end
  end

  #Update interests
  def update_interest
    @interest = Interest.find(params[:id_interest])
    @user = User.find(params[:id])
    @user.interests << @interest
    redirect_to perfil_path(@user.id), notice: 'Gusto agregado de forma exitosa'
  end

  def delete_interest
    @interest = Interest.find(params[:idinterest])
    @user = User.find(params[:id])
    @user.interests.delete(@interest)
    redirect_to perfil_path(@user.id), notice: 'El interés ha sido eliminado de forma exitosa'
  end

  # Avatar
  def update_avatar
    user_params = params.require(:user).permit(:avatar)
    @user = User.find(params[:user_id])
    @user.avatar.attach(user_params[:avatar])
    if @user.avatar.attached?
      redirect_to perfil_path(@user.id), notice: 'Tu imagen de perfil ha sido añadida exitosamente'
    else
      redirect_to perfil_path(@user.id), notice: 'Ocurrió un error al subir la imagen. Inténtalo nuevamente'
    end
  end

  def delete_avatar
    @user = User.find(params[:user_id])
    @user.avatar.purge
      redirect_to perfil_path(@user.id), notice: 'Tu imagen de perfil ha sido eliminada exitosamente'
  end

  #Delete
  def destroy
    @user = User.find(params[:id])
    @match_request_solicitante = MatchRequest.where('solicitante_id = ' + @user.id.to_s)
    @match_request_solicitado = MatchRequest.where('solicitado_id = ' + @user.id.to_s)

    @match_request_solicitante.each do |match_request|
      match_request.destroy
    end

    @match_request_solicitado.each do |match_request|
      match_request.destroy
    end

    @match_1 = Match.where('user1_id = ' + @user.id.to_s)
    @match_2 = Match.where('user2_id = ' + @user.id.to_s)
    
    @match_1.each do |match|
      match.destroy
    end

    @match_2.each do |match|
      match.destroy
    end

    @user.destroy
    redirect_to root_path, notice: 'Usuario eliminado con exito' 
  end
end

IIC2143 - Ingeniería de Software/app/views/perfil/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MatchMeat</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>
<body>

<div class="hero-body">
  <div class="container has-text-centered">
    <div class="column is-4 is-offset-4">
      <h3 class="title has-text-white">Editar Perfil</h3>
      <div class="box">
        <%= form_with(model: @user, url: perfil_path(@user.id), method: :patch) do |form| %>
          <div class="field">
            <div class= "control">
              <span class="icon is-small is-left">
                <i class="fas fa-user"></i>
              </span>
              Nombre:
              <%= form.text_field :nombre, autofocus: true, autocomplete: "nombre", placeholder: "Nombre", class: "input" %>
            </div>
          </div>

          <div class="field">
            <div class="control">
              <span class="icon is-small is-left">
                <i class="fas fa-envelope"></i>
              </span>
              Correo:
              <%= form.text_field :email, autofocus: true, autocomplete: "email", placeholder: "Email", class: "input" %>
            </div>
          </div>

          <div class="field">
            <div class="control">
              <span class="icon is-small is-left">
                <i class="fas fa-clipboard-list"></i>
              </span>
              Descripcion:
              <%= form.text_area :descripcion, autofocus: true, autocomplete: "descripcion", placeholder: "Descripcion", class: "input" %>
            </div>          
          </div>

          <div class="field">
            <div class="control">
              <span class="icon is-small is-left">
                <i class="far fa-id-card"></i>
              </span>
              Edad:
              <%= form.number_field :edad, autofocus: true, autocomplete: "edad", placeholder: "Edad", class: "input"%>
            </div>
          </div>

          <div class="field">
            <div class="control">
              <span class="icon is-small is-left">
                <i class="fas fa-mobile-alt"></i>
              </span>
              Numero celular:
              <%= form.text_field :telefono, autofocus: true, autocomplete: "telefono", placeholder: "Telefono", class: "input"%>
            </div>
          </div>

          <div class="field">
            <div class="control">
              <span class="icon is-small is-left">
                <i class="fas fa-home"></i>
              </span>
              Comuna: 
              <div class="select is-fullwidth">
                <%= form.select(:commune_id, Commune.all.collect {|c| [c.nombre, c.id]}) %>
              </div>
            </div>
          </div>

          <div class="field">
            <div class="control">
              <span class="icon is-small is-left">
                <i class="fas fa-venus-mars"></i>
              </span>
              Genero:
              <div class="select is-fullwidth">
                <%= form.select(:genero, ['Masculino', 'Femenino', 'Otro'])%>
              </div>
            </div>
          </div>

          <div class="button is-medium is-primary is-fullwidth" value="Ingresar">
            <%= form.submit "Guardar Cambios", class: "button is-medium is-primary is-fullwidth"%>
          </div>
        <% end %>
        <%= link_to 'Volver', perfil_path(@user.id), class: "button is-fullwidth is-danger is-light" %>
</body>
</html>

IIC2143 - Ingeniería de Software/app/views/perfil/index.html.erb
<section class="section">
<div class="box">
<h1 class="title is-5 has-text-centered">Usuarios</h1>

<table class="table is-fullwidth is-striped">
<thead>
    <tr>
    <th>Email</th>
    <th>Nombre</th>
    <th>Descripcion</th>
    <th>Edad</th>
    <th>Acciones</th>
    </tr>
</thead>

<tbody>
    <% @users.each do |usuario| %>
    <tr>
        <td><%= usuario.email %></td>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.descripcion%></td>
        <td><%= usuario.edad %></td>
        <td><%= link_to 'Eliminar cuenta', perfil_path(usuario.id),  method: :delete, class: "button is-danger",
                data: {confirm: "¿Estás seguro?"} %>
            <%= link_to 'Ver cuenta', perfil_path(usuario.id), class: "button is-primary"%></td>
    </tr>
    <% end %>
</tbody>
</table>

<%= link_to 'Volver al Panel', admin_path, class: "button is-link"%>
</div>
</section>

IIC2143 - Ingeniería de Software/app/views/perfil/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MatchMeat</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  <style>
    ul#interests li {
      display:inline;
    }
  </style>
</head>

<section class="hero is-danger">
  <div class="hero-body">
      <h1 class="title has-text-centered">Mi perfil</h1>
      <h2 class="subtitle has-text-centered">En esta sección puedes revisar tus datos, editarlos y subir una imágen que será mostrada a los demás usuarios. Acá también 
      puedes inscribir tu propio local.</h2>
  </div>
</section>

<div class="tabs is-centered">
  <ul>
    <li class="is-active"><a href="<%=perfil_path(current_user.id)%>">Mis Datos</a></li>
    <li><%= link_to 'Mis Comentarios', perfil_comentarios_path(current_user.id)%></li>
    <li><%= link_to 'Citas y Valoraciones Pendientes', perfil_valuations_path(current_user.id)%></li>
  </ul>
</div>


<section class="section">
  <div class="columns">
    <div class="column is-1"></div>
    <div class="column is-4">
      <div class="box">
        <h1 class="title has-text-centered">Mis datos</h1>
        <article class="media">
          <div class="media-content">
            <div class="content">
              <p><center>
                <strong>Nombre:</strong>
                <%= @user.nombre %>            
              </center></p>

              <p><center>
                <strong>Email:</strong>
                <%= @user.email %>
              </center></p>

              <p><center>
                <strong>Descripcion:</strong>
                <%= @user.descripcion %>
              </center></p>

              <p><center>
                <strong>Edad:</strong>
                <%= @user.edad %>
              </center></p>

              <p><center>
                <strong>Telefono:</strong>
                <%= @user.telefono %>
              </center></p>

              <p><center>
                <strong>Comuna:</strong>
                <%= @commune.nombre%>
              </center></p>

              <p><center>
                <strong>Género:</strong>
                <%= @user.genero %>
              </center></p>

              <p><center>
                <% if not @interests_user.nil?%>
                  <strong>Mis Gustos:</strong>
                  <br>
                  <br>
                  <div class="field is-grouped is-grouped-multiline">    
                    <% @interests_user.each do |interest| %>
                      <div class="control">
                        <div class="tags has-addons">
                          <a class="tag is-danger"><%= interest.nombre %></a>
                          <a href="<%=perfil_delete_interest_path(@user.id, interest.id)%>" class="tag is-delete"></a>
                        </div>
                      </div>
                    <% end %>
                  </div>
                <% end %>
                <hr>
                <strong>Agregar gusto:</strong>
                <br>
                <br>
                <%= form_with(model: @interests_user, url: perfil_edit_interest_path(@user.id), method: :patch) do |form| %>
                  <div class="field">
                    <div class="control">
                      <div class="select is-fullwidth is-danger">
                        <select name='id_interest'>
                          <% @interests_not_user.each do |interest|%>
                            <option value="<%= interest.id %>"><%= interest.nombre %></option>
                          <% end %>
                        </select>
                      </div>
                    </div>
                  </div>
                  
                  <div class="button is-danger" value="Guardar interes">
                    <%= form.submit "Guardar gusto", class: "button is-danger"%>
                  </div>
                <% end %>
                <br>
                

              </center></p>     
            </div>
          </div>
        </article>
      </div>
    </div>

    <div class="column is-2">
      <div class="box">
        <h1 class="title has-text-centered">Acciones</h1>
        <center>
        <% if @local %>
          <%= link_to 'Ver mi local', local_path(@local.id), class: 'button is-primary is-rounded'%>
        <% else%>
          <%= link_to 'Inscribir un local', new_local_path, class: 'button is-primary is-rounded' %>
        <%end%>
        </center></br>
        <center>
        <%= link_to 'Editar perfil', perfil_edit_path(@user.id), class: 'button is-link is-rounded' %>
        </center></br>
        <center>
        <%= link_to 'Eliminar cuenta', perfil_path(@user.id), class: 'button is-danger is-rounded', method: :delete, data: { confirm: "¿Estas seguro? \n 
        Esta acción no es reversible" }%>
        </center></hr>
      </div>
    </div>

    <div class="column is-4">
      <div class="box">
        <h1 class="title has-text-centered">Imagen de perfil</h1>
        <center>
        <figure class="image is-4by5">
          <% unless @user.avatar.attached? %>
            <img src="https://bulma.io/images/placeholders/480x600.png" width="480" height="600">
          <% else %>
            <%= image_tag(@user.match_avatar) %>
          <% end %>
        </figure>
        </center>
        
        <%= form_with(model: @user, url: perfil_update_avatar_path(@user.id), method: :patch) do |form| %>
          <div id="file-js-example" class="file is-centered">
            <label class="file-label">
              <%= form.file_field :avatar, accept: 'image/jpeg', class: "file-input"%>
              <span class="file-cta">
                <span class="file-icon">
                  <i class="fas fa-upload"></i>
                </span>
                <span class="file-label">
                  Elige un archivo...
                </span>
              </span>
            </label>
          </div>
          <br>
          <center>
            <div class="button is-primary">
              <%= form.submit "Guardar Imagen", class: "button is-primary"%>
            </div>
          </center>
        <% end %>

        <br>
        <center>
          <button class="button is-danger" <% unless @user.avatar.attached? %> disabled <% end %>>
            <%= link_to_if @user.avatar.attached?, "Eliminar imagen", perfil_delete_avatar_path(@user.id), method: :delete, class: "button is-danger"%>
          </button>
        </center>
      </div>
    </div>
  
    <div class="column is-1"></div>
  </div>
</section>

IIC2143 - Ingeniería de Software/app/views/perfil/show_incomplete.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MatchMeat</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  <style>
    ul#interests li {
      display:inline;
    }
  </style>
</head>

<section class="hero is-danger">
  <div class="hero-body">
      <h1 class="title has-text-centered">Perfil de <%= @user.nombre %></h1>
      <div class="buttons is-centered">
        <% if current_user.admin%>
          <%= link_to "Volver al Panel", admin_usuarios_path, class: "button is-link is-rounded"%>
        <% else %>
          <%= link_to "Volver", match_info_path(current_user.id), class: "button is-link is-rounded"%>
        <% end %>
      </div>
  </div>
</section>

<section class="section">
  <div class="columns">
    <div class="column is-2"></div>
    <div class="column is-4">
      <div class="box">
        <h1 class="title has-text-centered">Datos</h1>
        <article class="media">
          <div class="media-content">
            <div class="content">
              <p><center>
                <strong>Nombre:</strong>
                <%= @user.nombre %>            
              </center></p>

              <p><center>
                <strong>Descripcion:</strong>
                <%= @user.descripcion %>
              </center></p>

              <p><center>
                <strong>Edad:</strong>
                <%= @user.edad %>
              </center></p>

              <p><center>
                <strong>Comuna:</strong>
                <%= @commune.nombre%>
              </center></p>

              <p><center>
                <strong>Género:</strong>
                <%= @user.genero %>
              </center></p>

              <p><center>
                <% if not @interests_user.nil?%>
                  <strong>Gustos:</strong>
                  <br>
                  <br>
                  <div class="field is-grouped is-grouped-multiline">    
                    <% @interests_user.each do |interest| %>
                      <div class="control">
                        <div class="tags has-addons">
                          <a class="tag is-danger"><%= interest.nombre %></a>
                        </div>
                      </div>
                    <% end %>
                  </div>
                <% end %>
                <hr>
                <br>
                <br>
                

              </center></p>     
            </div>
          </div>
        </article>
      </div>
    </div>

    <div class="column is-4">
      <div class="box">
        <h1 class="title has-text-centered">Imágen de perfil</h1>
        <center>
          <figure class="image is-4by5">
            <% unless @user.avatar.attached? %>
              <img src="https://bulma.io/images/placeholders/480x600.png" width="480" height="600">
            <% else %>
              <%= image_tag(@user.match_avatar) %>
            <% end %>
          </figure>
        </center>

      </div>
    </div>
  
    <div class="column is-2"></div>
  </div>
</section>

IIC2143 - Ingeniería de Software/app/views/perfil/valuations.html.erb
<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>

<section class="hero is-danger">
  <div class="hero-body">
    <div class="container">
      <h1 class="title has-text-centered"> Citas y Valoraciones Pendientes </h1>
      <h2 class="subtitle has-text-centered"> En esta sección puedes ver tus citas pendientes, así como dejar una valoración cuando la fecha ya ha pasado.
      Si te dejaron plantado o la cita no tuvo éxito, tienes la opción para hacernos saber eso :(</h2>
    </div>
  </div>
</section>

<div class="tabs is-centered">
  <ul>
    <li><%= link_to "Mis Datos", perfil_path(current_user.id)%></li>
    <li><%= link_to 'Mis Comentarios', perfil_comentarios_path(current_user.id)%></li>
    <li class="is-active"><%= link_to 'Citas y Valoraciones Pendientes', perfil_valuations_path(current_user.id)%></li>
  </ul>
</div>

<section class="section">
  <div class="columns">
    <div class="column"></div>
    <div class="column is-two-thirds">
      <div class="box">
      <div class="content">
        <table class="table">
          <thead>
            <tr>
              <th> Afortunad@ </th>
              <th> Local  </th>
              <th> Fecha </th>
              <th> Acción </th>
            </tr>
          </thead>
          <tbody>
            <% @pending_valuations.each do |valuation|%>
              <% @disabled = (valuation.fecha >= @current_date)%>
              <% user = User.find(valuation.lucky_id)%>
              <% local = Local.find(valuation.local_id)%>
            <tr>
              <td>
                <% if user %>
                  <%= link_to valuation.nombre, perfil_path(valuation.lucky_id), target: :_blank %>
                <% else %>
                  <%= valuation.nombre %>
                <% end %>
              </td>
              <td>
                <% if local %>
                  <%= link_to valuation.local_name, local_path(valuation.local_id), target: :_blank %>
                <% else %>
                  <%= valuation.local_name %>
                <% end %>
              </td>
              <td> <%= valuation.fecha %></td>
              <td> 
                <button class="button is-primary" <%if @disabled%> disabled <% end %>>
                  <%= link_to_unless @disabled, 'Dejar valoración', edit_local_valoracione_path(valuation.local.id, valuation.id), class: "button is-primary"%>
                </button>
                <button class="button is-danger" <% if @disabled %> disabled <% end %>>
                  <%= link_to_unless @disabled, "Cita no realizada", local_valoracione_path(valuation.local.id, valuation.id), class: "button is-danger",
                  method: :delete, data: { confirm: "¿Estas seguro?"}%>
                </button>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      </div>
    </div>
    <div class="column"></div>
  </div>
</section>